version: "3"

services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: blogs_api
    restart: unless-stopped
  myAdmin:
    image: phpmyadmin:latest
    container_name: myAdmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 123
    ports:
      - 8080:80
    depends_on:
      - db
    restart: unless-stopped
